name = "cho-book"
account_id = "bbd5aea1ec9f622347ed15a67fcfd99d"

main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"
compatibility_date = "2023-07-17"

build.command = "npm run build"

[[ d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "cho_book"
database_id = "7f3bf433-8767-4415-aa46-291ff52e611e"
preview_database_id = "99e32dc4-e103-4e4b-b25d-46e5a39e82f4"
