name = "cho-book"
account_id = "bbd5aea1ec9f622347ed15a67fcfd99d"

main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"
compatibility_date = "2023-07-17"

build.command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "cho-book-dev"
database_id = "4c4d6f03-17e8-40fd-9e9e-264bce2300bd"

[env.prod]
[[ env.prod.d1_databases ]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "cho-book"
database_id = "fcc7c1e2-49cc-452b-aaa4-dcfb236f4473"
