name: Deploy(prod)

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '22'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    environment:
      name: production
      url: https://cho-book.mazrean.com
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: ./package-lock.json
      - run: npm ci
      - run: npm run deploy:prod
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
          RAKUTEN_APP_ID: ${{ secrets.RAKUTEN_APP_ID }}
